apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200