apiVersion: v1
kind: Service
metadata:
  name: express-backend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: express-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000